/** One SDK-addressed node, its remote keys, and native OpenTofu state lock. */
import {chmodSync,readdirSync,constants,openSync,closeSync,fstatSync,fchmodSync,ftruncateSync,existsSync,lstatSync,mkdirSync,readFileSync,renameSync,rmSync,writeFileSync} from 'node:fs';
import {join,resolve,isAbsolute} from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
import recipes from '../resources/provider-recipes.json';
import templates from '../resources/templates.json';
import {registry} from './index.ts';
import {provider_request} from './provider-request.ts';
import {backend_plan} from './rendering.ts';
import {commandFailure,failure} from './diagnostics.ts';
import {executeBackendCommand,parseStateEnvelope,stateOutputs,type BackendRunner} from './backend.ts';
type Map=Record<string,any>;type Env=Record<string,string|undefined>;
const safe=(v:unknown):v is string=>typeof v==='string'&&/^[A-Za-z0-9][A-Za-z0-9_-]{0,62}$/.exec(v)?.[0]===v;
function demand(v:unknown,message:string):asserts v{if(!v)throw Error(message);}
const object=(v:unknown):v is Map=>v!==null&&typeof v==='object'&&!Array.isArray(v);
function privateWrite(path:string,value:string){const fd=openSync(path,constants.O_WRONLY|constants.O_CREAT|constants.O_NOFOLLOW|constants.O_NONBLOCK,0o600);try{const info=fstatSync(fd);demand(info.isFile()&&info.nlink===1,'unsafe compute file');fchmodSync(fd,0o600);ftruncateSync(fd,0);writeFileSync(fd,value);}finally{closeSync(fd);}}
function privateRead(path:string){const fd=openSync(path,constants.O_RDONLY|constants.O_NOFOLLOW|constants.O_NONBLOCK);try{demand(fstatSync(fd).isFile(),'unsafe compute file');return readFileSync(fd,'utf8');}finally{closeSync(fd);}}
function directory(path:string){const full=resolve(path);let cursor=full;const paths=[];while(cursor!==resolve(cursor,'..')){paths.unshift(cursor);cursor=resolve(cursor,'..');}for(const p of paths){if(existsSync(p))demand(lstatSync(p).isDirectory()&&!lstatSync(p).isSymbolicLink(),'unsafe compute directory');else mkdirSync(p,{mode:0o700});}chmodSync(full,0o700);}
export function node_layout(opts:Map,request:Map){
 demand(safe(opts.profile)&&safe(request.node_id),'invalid compute identity');demand(typeof request.state_filename==='string'&&/^[A-Za-z0-9][A-Za-z0-9_.-]*\.tfstate$/.exec(request.state_filename)?.[0]===request.state_filename,'invalid node state filename');demand(typeof request.workdir==='string'&&isAbsolute(request.workdir)&&!/[\\\0]/.test(request.workdir)&&resolve(request.workdir)===request.workdir,'SDK workdir is required');
 const prefix=Object.hasOwn(opts,'s3-prefix')?opts['s3-prefix']:'';demand(typeof prefix==='string'&&(prefix===''||prefix.split('/').every(p=>/^[A-Za-z0-9][A-Za-z0-9_.-]*$/.exec(p)?.[0]===p)),'invalid S3 prefix');const base=[prefix,opts.profile].filter(Boolean).join('/');
 return {directory:resolve(request.workdir,opts.profile,request.node_id),state_key:base+'/'+request.state_filename,key_objects:{} as Record<string,string>};
}
function merge(target:Map,source:Map){for(const [k,v] of Object.entries(source)){if(!Object.hasOwn(target,k))target[k]=structuredClone(v);else if(object(target[k])&&object(v))merge(target[k],v);else demand(JSON.stringify(target[k])===JSON.stringify(v),'conflicting template '+k);}}
const REGISTRATIONS:Map={aws:'aws_key_pair',digitalocean:'digitalocean_ssh_key',hcloud:'hcloud_ssh_key',vultr:'vultr_ssh_key'};
function publicIdentity(value:Map){demand(object(value)&&Object.keys(value).every(k=>['reference','public_key','fingerprint','status'].includes(k))&&typeof value.reference==='string'&&value.reference.trim(),'SSH resource reference required');const parts=typeof value.public_key==='string'?value.public_key.split(/\s+/):[];demand(parts.length===2&&parts[0]==='ssh-ed25519','ED25519 public identity required');const blob=Buffer.from(parts[1],'base64');demand(blob.length===51&&blob.subarray(0,19).toString('hex')==='0000000b7373682d6564323535313900000020','invalid ED25519 identity');demand(value.fingerprint==='SHA256:'+createHash('sha256').update(blob).digest('base64').replace(/=+$/,''),'SSH fingerprint mismatch');return value;}
function registrationIdentity(provider:string,request:Map,identity:Map){const value=request.ssh_registration;if(!REGISTRATIONS[provider]){demand(value===undefined,'provider consumes public identity directly');return null;}demand(object(value)&&value.status==='ready'&&value.provider===provider&&value.ssh_resource_reference===identity.reference&&value.fingerprint===identity.fingerprint&&typeof value.id==='string'&&value.id.trim()&&typeof value.reference==='string'&&value.reference.trim(),'matching SSH registration required');return value;}
export function node_plan(opts:Map,request:Map){
 demand(object(opts)&&object(request),'invalid node request');demand(!['ssh-key-path','ssh-private-key-path','ssh-public-key-path'].some(k=>Object.hasOwn(opts,k)),'external SSH keys are outside the single-node contract');demand(!Object.hasOwn(opts,'compute-require-existing-state')||typeof opts['compute-require-existing-state']==='boolean','invalid existing-state requirement');demand(!JSON.stringify([opts,request]).includes('${')&&!JSON.stringify([opts,request]).includes('%{')&&!JSON.stringify([opts,request]).includes('\\u0000'),'Terraform expression in caller input');demand(Object.keys(request).every(k=>['node_id','state_filename','workdir','security','network','ssh_resource','ssh_registration'].includes(k)),'unsupported node field');const layout=node_layout(opts,request),provider=opts['provider-compute'];const identity=publicIdentity(request.ssh_resource),registration=registrationIdentity(provider,request,identity);demand(![(registry.compute as Map)[provider]?.['ssh-setting'],...Object.keys((registry.compute as Map)[provider]?.['ssh-aliases']??{}),provider+'-ssh-private-key'].some(k=>k&&Object.hasOwn(opts,k)),'external SSH keys are outside the single-node contract');demand(!Object.hasOwn(opts,'compute-role-settings'),'topology settings are outside the single-node contract');const recipe=(recipes as Map)[provider];demand(recipe,'unsupported provider');const scoped=opts.profile+'-'+request.node_id;demand(safe(scoped),'combined identity too long');
 const scopedOpts={...opts,profile:scoped},placeholder='ssh-ed25519 COLORS_COMPUTE_REMOTE_KEY';const base={node_id:request.node_id,name:scoped,key:{mode:'managed',public_key:placeholder},network:structuredClone(request.network??{mode:recipe.network_mode}),security:structuredClone(request.security)};
 const sharedDocs=provider_request(scopedOpts,'shared',base).documents,substitutions:Map={[placeholder]:identity.public_key};if(registration)for(const field of ['id','key_name'])substitutions['${'+REGISTRATIONS[provider]+'.machine.'+field+'}']=registration.id;let ordinal=0;
 function sentinels(v:any):any{if(typeof v==='string'&&v.includes('${')){const token='colors-compute-reference-'+ordinal++;substitutions[token]=v;return token;}if(Array.isArray(v))return v.map(sentinels);if(object(v))return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,sentinels(x)]));return v;}
 const shared:Map={};for(const doc of Object.values(sharedDocs) as Map[])for(const [k,out] of Object.entries(doc.output??{}) as [string,Map][])shared[k]=sentinels(out.value);
 const nodeDocs=provider_request(scopedOpts,'node',base,shared).documents,document:Map={};for(const doc of Object.values(sharedDocs) as Map[]){const value=structuredClone(doc);delete value.output;merge(document,value);}for(const doc of Object.values(nodeDocs) as Map[])merge(document,doc);
 function replace(v:any):any{if(typeof v==='string')return Object.hasOwn(substitutions,v)?replace(substitutions[v]):v;if(Array.isArray(v))return v.map(replace);if(object(v))return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,replace(x)]));return v;}
 const combined=replace(document);if(registration)delete combined.resource[REGISTRATIONS[provider]];
 combined.output.compute_identity={value:{profile:opts.profile,node_id:request.node_id,state_filename:request.state_filename,provider,ssh_resource_reference:identity.reference,ssh_fingerprint:identity.fingerprint}};

 const backend=opts['provider-backend']==='local'?{terraform:{backend:{local:{path:join(layout.directory,request.state_filename)}}}}:backend_plan(opts,layout.state_key).config;return {status:'planned',...layout,documents:{'compute.tf.json':combined,'backend.tf.json':backend}};
}
export function build_node(opts:Map,request:Map,planner=node_plan){const plan=planner(opts,request);directory(plan.directory);const existing=join(plan.directory,'compute.tf.json');if(existsSync(existing)){const previous=JSON.parse(privateRead(existing));demand(JSON.stringify(previous.output?.compute_identity)===JSON.stringify(plan.documents['compute.tf.json'].output.compute_identity),'existing unit identity cannot change');}const backend=join(plan.directory,'backend.tf.json');if(existsSync(backend))demand(JSON.stringify(JSON.parse(privateRead(backend)))===JSON.stringify(plan.documents['backend.tf.json']),'existing unit backend cannot change');for(const [name,doc] of Object.entries(plan.documents))privateWrite(join(plan.directory,name),JSON.stringify(doc,null,2)+'\n');return {...plan,status:'built'};}
function runtimeEnv(opts:Map,source:Env){const env:Record<string,string>={};for(const [k,v] of Object.entries(source))if(v!==undefined&&!/^(TF_|TOFU_|COLORS_PAR_)/.test(k))env[k]=v;for(const [secret,name] of Object.entries((registry.compute as Map)[opts['provider-compute']]['tofu-env']) as [string,string][]){const value=source['COLORS_PAR_'+secret.toUpperCase().replaceAll('-','_')];demand(value&&value.trim(),'missing compute credential');env[name]=value;}Object.assign(env,{TF_IN_AUTOMATION:'1',TF_INPUT:'0',TF_WORKSPACE:'default'});return env;}
function planAllowed(raw:string,operation:string){const p=JSON.parse(raw);demand(object(p)&&object(p.planned_values)&&typeof p.format_version==='string','invalid plan');const permitted=operation==='delete'?['no-op','read','delete']:['no-op','read','create','update'];demand(Array.isArray(p.resource_changes??[]),'invalid plan');for(const r of p.resource_changes??[])demand(Array.isArray(r.change?.actions)&&r.change.actions.length===1&&permitted.includes(r.change.actions[0]),'replacement refused');}
function normalized(params:Map,environment:Env){
 demand(object(params),'invalid compute outputs');const allowed=new Set<string>();for(const [stage,documents] of Object.entries((templates as Map)[params.provider]??{}) as [string,Map][])if(stage.startsWith('node'))for(const document of Object.values(documents) as Map[])for(const key of Object.keys(document.output?.params?.value??{}))allowed.add(key);
 demand(Object.keys(params).every(k=>allowed.has(k)),'unexpected compute output');const result=structuredClone(params);for(const k of ['provider','name','ip','user','sudoer'])demand(typeof result[k]==='string'&&result[k].trim(),'incomplete compute outputs');const text=JSON.stringify(result);demand(!text.includes('-----BEGIN ')&&!['"private_key"','"private_key_openssh"','"secret_key"','"access_key"'].some(marker=>text.toLowerCase().includes(marker)),'secret compute output');for(const [k,v] of Object.entries(environment))if(v&&(k.startsWith('COLORS_PAR_')||/SECRET|TOKEN|PASSWORD|ACCESS_KEY|API_KEY/.test(k)))demand(!text.includes(v),'credential compute output');return result;
}
async function statePresence(opts:Map,request:Map,source:Env,runner:BackendRunner,env:Record<string,string>){
 const layout=node_layout(opts,request),b=opts['provider-backend'];
 if(b==='local'){const path=join(layout.directory,request.state_filename);if(!existsSync(path))return false;demand(lstatSync(path).isFile()&&!lstatSync(path).isSymbolicLink(),'unsafe local state');readFileSync(path);return true;}
 const remoteEnv={...env};for(const k of Object.keys(remoteEnv))if(k.startsWith('TF_'))delete remoteEnv[k];
 if(['r2','oci'].includes(b)){for(const k of Object.keys(remoteEnv))if(k.startsWith('AWS_')&&k!=='AWS_CA_BUNDLE')delete remoteEnv[k];remoteEnv.AWS_ACCESS_KEY_ID=source['COLORS_PAR_'+b.toUpperCase()+'_ACCESS_KEY_ID']!;remoteEnv.AWS_SECRET_ACCESS_KEY=source['COLORS_PAR_'+b.toUpperCase()+'_SECRET_ACCESS_KEY']!;}
 const path=join(layout.directory,'.state-probe-'+randomUUID());
 try{privateWrite(path,'');if(b==='gcs'){const r=await runner(['gcloud','storage','cp','gs://'+opts['gcs-bucket']+'/'+layout.state_key+'/default.tfstate',path],{cwd:layout.directory,env:remoteEnv,timeoutMs:120000});if(r.exit===0)return true;if(!/No URLs matched/.test(r.err))throw commandFailure(['gcloud','storage','cp'],layout.directory,remoteEnv,r,opts,source);const bucket=await runner(['gcloud','storage','buckets','describe','gs://'+opts['gcs-bucket'],'--format=json'],{cwd:layout.directory,env:remoteEnv,timeoutMs:120000});if(bucket.exit!==0)throw commandFailure(['gcloud','storage','buckets'],layout.directory,remoteEnv,bucket,opts,source);demand(JSON.parse(bucket.out).name===opts['gcs-bucket'],'state bucket unreadable');return false;}
 const config=backend_plan(opts,layout.state_key).config.terraform.backend.s3;
 const r=await runner(['aws','s3api','get-object','--bucket',config.bucket,'--key',layout.state_key,'--region',config.region,...(config.endpoints?.s3?['--endpoint-url',config.endpoints.s3]:[]),path],{cwd:layout.directory,env:remoteEnv,timeoutMs:120000});if(r.exit===0)return true;if(!/^\s*(?:aws: \[ERROR\]: )?An error occurred \(NoSuchKey\) when calling the GetObject operation(?: \(reached max retries: [0-9]+\))?:/.test(r.err))throw commandFailure(['aws','s3api','get-object'],layout.directory,remoteEnv,r,opts,source);return false;
 }finally{rmSync(path,{force:true});}
}
export async function compute_node(opts:Map,request:Map,operation='create',environment:Env=process.env,deps:Map={}){
 let credentialPath:string|undefined;let stage='validate',infrastructure_changes='none';let cancelled=false;try{
 const planner=deps._planner??node_plan,normalize=deps._normalize??normalized;demand(['build','create','inspect','delete'].includes(operation),'unsupported operation');planner(opts,request);if(operation==='build'){stage='build';return build_node(opts,request,planner);}demand(operation!=='delete'||opts['compute-prevent-destroy']===false,'destruction protected');demand(!Object.hasOwn(opts,'compute-require-existing-state')||typeof opts['compute-require-existing-state']==='boolean','invalid existing-state requirement');
 stage='build';const plan=build_node(opts,request,planner);stage='credentials';const env=runtimeEnv(opts,environment),rawRunner:BackendRunner=deps.runner??executeBackendCommand,settings:Map={};const runner:BackendRunner=async(args,options)=>{try{return await rawRunner(args,options);}catch(error){if(error instanceof Error&&error.name==='AbortError')throw error;throw commandFailure(args,options.cwd,options.env,{},opts,environment);}};for(const [variable,option] of Object.entries(backend_plan(opts,plan.state_key).credential_bindings)){demand(environment[variable]?.trim(),'missing backend credential');settings[option]=environment[variable];}credentialPath=join(plan.directory,'credentials.tfbackend.json');privateWrite(credentialPath,JSON.stringify(settings));
 const execute=async(args:string[],timeoutMs=120000)=>{stage=args[0]==='show'?'plan-validation':args[0]==='state'?'state':args[0];for(const name of ['approved.tfplan','.terraform.lock.hcl',request.state_filename,request.state_filename+'.backup','.terraform/terraform.tfstate']){const path=join(plan.directory,name);try{const st=lstatSync(path);demand(st.isFile()&&!st.isSymbolicLink()&&st.nlink===1,'unsafe OpenTofu file');}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}}const data=join(plan.directory,'.terraform');try{const st=lstatSync(data);demand(st.isDirectory()&&!st.isSymbolicLink(),'unsafe OpenTofu directory');}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}stage=args[0]==='show'?'plan-validation':args[0]==='state'?'state':args[0];if(args[0]==='apply')infrastructure_changes='possible';const r=await runner(['tofu',...args],{cwd:plan.directory,env,timeoutMs});for(const file of readdirSync(plan.directory)){const path=join(plan.directory,file);if(lstatSync(path).isFile()&&!lstatSync(path).isSymbolicLink())chmodSync(path,0o600);}if(r.exit!==0)throw commandFailure(['tofu',...args],plan.directory,env,r,opts,environment);return r.out;};await execute(['init','-input=false','-no-color','-reconfigure','-backend-config='+credentialPath]);stage='state';const present=await statePresence(opts,request,environment,runner,env);const before=present?await execute(['state','pull']):'';let current:Map|undefined;
 // Presence was independently established. An empty-lineage synthetic snapshot
 // here is inconsistent with that observation and must fail strict validation.
 if(before.trim())current=parseStateEnvelope(before).document;
 demand(!current||current.resources.length>0||Object.keys(current.outputs).length===0,'empty resource state has leftover outputs');if(operation==='inspect'&&present&&current&&current.resources.length===0&&Object.keys(current.outputs).length===0)return {status:'destroyed',directory:plan.directory};const populated=current&&current.resources.length>0;const identity=plan.documents['compute.tf.json'].output.compute_identity.value;if(populated){demand(Object.entries(identity).every(([k,v])=>current!.outputs.compute_identity?.value?.[k]===v),'state identity mismatch; explicit recovery required');}demand(!populated||current!.outputs.params?.value?.provider===opts['provider-compute'],'state provider mismatch');demand(operation!=='create'||opts['compute-require-existing-state']!==true||populated,'required state absent');
 if(operation==='inspect'){demand(populated,'state absent');return {status:'ready',directory:plan.directory,params:normalize(current!.outputs.params.value,environment)};}
 if(operation==='delete'&&!populated){demand(present&&current&&Object.keys(current.outputs).length===0,'absent state requires explicit recovery');stage='cleanup';return {status:'destroyed',directory:plan.directory};}
 const planPath=join(plan.directory,'approved.tfplan');await execute(['plan','-input=false','-no-color','-out='+planPath,...(operation==='delete'?['-destroy']:[])],1800000);planAllowed(await execute(['show','-json',planPath]),operation);await execute(['apply','-input=false','-no-color',planPath],1800000);const after=await execute(['state','pull']),final=parseStateEnvelope(after);
 if(operation==='delete'){demand(final.document.resources.length===0,'destruction incomplete');stage='cleanup';return {status:'destroyed',directory:plan.directory};}
 demand(final.params.provider===opts['provider-compute']&&final.params.node_id===request.node_id&&Object.entries(identity).every(([k,v])=>final.document.outputs.compute_identity?.value?.[k]===v),'invalid compute outputs');const outputs=opts['provider-backend']==='local'?{params:final.params}:stateOutputs(after);const secrets=Object.entries(environment).filter(([k,v])=>v&&(/SECRET|TOKEN|PASSWORD|ACCESS_KEY|API_KEY/.test(k))).map(([,v])=>v!);demand(!secrets.some(v=>JSON.stringify(outputs).includes(v)),'credential in compute output');return {status:'ready',directory:plan.directory,params:normalize(final.params,environment)};
 }catch(error){if(error instanceof Error&&error.name==='AbortError'){cancelled=true;throw error;}return failure(error,stage,infrastructure_changes);}finally{if(credentialPath)try{rmSync(credentialPath,{force:true});}catch(error){if(!cancelled)return failure(error,'cleanup',infrastructure_changes);}}
}

function registrationRequest(request:Map){demand(Object.keys(request).length===4&&['name','workdir','state_filename','ssh_resource'].every(k=>Object.hasOwn(request,k))&&safe(request.name),'invalid SSH registration request');return {node_id:'registration-'+request.name,workdir:request.workdir,state_filename:request.state_filename,ssh_resource:request.ssh_resource};}
function registrationPlan(opts:Map,internal:Map){const provider=opts['provider-compute'];demand(REGISTRATIONS[provider],'provider needs no SSH registration');const identity=publicIdentity(internal.ssh_resource),name=internal.node_id;demand(safe(opts.profile+'-'+name)&&!JSON.stringify([opts,internal]).includes('${')&&!JSON.stringify([opts,internal]).includes('%{'),'invalid registration identity');const layout=node_layout(opts,internal),root:Map={};for(const document of Object.values((templates as Map)[provider]['shared-keygen']) as Map[])merge(root,Object.fromEntries(Object.entries(document).filter(([k])=>['terraform','provider'].includes(k))));if(provider==='aws'){demand(typeof opts['aws-region']==='string'&&opts['aws-region'].trim(),'AWS region required');root.provider.aws.region=opts['aws-region'];}root.output={compute_identity:{value:{profile:opts.profile,node_id:name,state_filename:internal.state_filename,provider,ssh_resource_reference:identity.reference,ssh_fingerprint:identity.fingerprint}}};const backend=opts['provider-backend']==='local'?{terraform:{backend:{local:{path:join(layout.directory,internal.state_filename)}}}}:backend_plan(opts,layout.state_key).config;const plan={status:'planned',...layout,documents:{'compute.tf.json':root,'backend.tf.json':backend}};const resource={[provider==='aws'?'key_name':'name']:opts.profile+'-'+name,[provider==='vultr'?'ssh_key':'public_key']:identity.public_key,lifecycle:{prevent_destroy:opts['compute-prevent-destroy']??true}};root.resource={[REGISTRATIONS[provider]]:{machine:resource}};delete root.data;delete root.locals;root.output={compute_identity:{value:{...root.output.compute_identity.value,kind:'ssh-registration',provider_scope:provider==='aws'?opts['aws-region']:provider}},params:{value:{provider,node_id:name,id:'${tostring('+REGISTRATIONS[provider]+'.machine.'+(provider==='aws'?'key_name':'id')+')}'}}};return plan;}
export function registration_plan(opts:Map,request:Map){return registrationPlan(opts,registrationRequest(request));}
export function build_registration(opts:Map,request:Map){return build_node(opts,registrationRequest(request),registrationPlan);}
export async function compute_registration(opts:Map,request:Map,operation='create',environment:Env=process.env,deps:Map={}){const result:any=await compute_node(opts,registrationRequest(request),operation,environment,{...deps,_planner:registrationPlan,_normalize:(params:Map)=>{demand(object(params)&&Object.keys(params).every(k=>['provider','node_id','id'].includes(k))&&typeof params.id==='string'&&params.id.trim(),'invalid registration output');return params;}});if(result.status==='ready'){const identity=publicIdentity(request.ssh_resource);return {status:'ready',directory:result.directory,reference:registration_plan(opts,request).state_key,provider:opts['provider-compute'],ssh_resource_reference:identity.reference,fingerprint:identity.fingerprint,id:result.params.id};}return result;}
