/** One SDK-addressed node, its remote keys, and native OpenTofu state lock. */
import {chmodSync,readdirSync,constants,openSync,closeSync,fstatSync,fchmodSync,ftruncateSync,existsSync,lstatSync,mkdirSync,readFileSync,renameSync,rmSync,writeFileSync} from 'node:fs';
import {join,resolve,isAbsolute} from 'node:path';
import {randomUUID} from 'node:crypto';
import recipes from '../resources/provider-recipes.json';
import templates from '../resources/templates.json';
import {registry} from './index.ts';
import {provider_request} from './provider-request.ts';
import {backend_plan} from './rendering.ts';
import {executeBackendCommand,parseStateEnvelope,stateOutputs,type BackendRunner} from './backend.ts';
type Map=Record<string,any>;type Env=Record<string,string|undefined>;
const safe=(v:unknown):v is string=>typeof v==='string'&&/^[A-Za-z0-9][A-Za-z0-9_-]{0,62}$/.exec(v)?.[0]===v;
function demand(v:unknown,message:string):asserts v{if(!v)throw Error(message);}
const object=(v:unknown):v is Map=>v!==null&&typeof v==='object'&&!Array.isArray(v);
function privateWrite(path:string,value:string){const fd=openSync(path,constants.O_WRONLY|constants.O_CREAT|constants.O_NOFOLLOW|constants.O_NONBLOCK,0o600);try{const info=fstatSync(fd);demand(info.isFile()&&info.nlink===1,'unsafe compute file');fchmodSync(fd,0o600);ftruncateSync(fd,0);writeFileSync(fd,value);}finally{closeSync(fd);}}
function privateRead(path:string){const fd=openSync(path,constants.O_RDONLY|constants.O_NOFOLLOW|constants.O_NONBLOCK);try{demand(fstatSync(fd).isFile(),'unsafe compute file');return readFileSync(fd,'utf8');}finally{closeSync(fd);}}
function directory(path:string){const full=resolve(path);let cursor=full;const paths=[];while(cursor!==resolve(cursor,'..')){paths.unshift(cursor);cursor=resolve(cursor,'..');}for(const p of paths){if(existsSync(p))demand(lstatSync(p).isDirectory()&&!lstatSync(p).isSymbolicLink(),'unsafe compute directory');else mkdirSync(p,{mode:0o700});}chmodSync(full,0o700);}
export function node_layout(opts:Map,request:Map){
 demand(safe(opts.profile)&&safe(request.node_id),'invalid compute identity');demand(typeof request.state_filename==='string'&&/^[A-Za-z0-9][A-Za-z0-9_.-]*\.tfstate$/.exec(request.state_filename)?.[0]===request.state_filename,'invalid node state filename');demand(typeof request.workdir==='string'&&isAbsolute(request.workdir)&&!/[\\\0]/.test(request.workdir)&&resolve(request.workdir)===request.workdir,'SDK workdir is required');
 const prefix=Object.hasOwn(opts,'s3-prefix')?opts['s3-prefix']:'';demand(typeof prefix==='string'&&(prefix===''||prefix.split('/').every(p=>/^[A-Za-z0-9][A-Za-z0-9_.-]*$/.exec(p)?.[0]===p)),'invalid S3 prefix');const base=[prefix,opts.profile].filter(Boolean).join('/');
 return {directory:resolve(request.workdir,opts.profile,request.node_id),state_key:base+'/'+request.state_filename,key_objects:(opts['provider-backend']==='local'?{}:{private:base+'/'+request.node_id+'/ssh-key',public:base+'/'+request.node_id+'/ssh-key.pub'}) as Record<string,string>};
}
function storage(opts:Map){const b=opts['provider-backend'];demand(!['s3','r2','oci','local'].includes(b)||!['ssh-s3-bucket','ssh-s3-region','ssh-s3-endpoint'].some(k=>Object.hasOwn(opts,k)),'SSH storage must use the state backend');const explicit=Object.hasOwn(opts,'ssh-s3-bucket');demand(explicit||['s3','r2','oci'].includes(b),'SSH S3 storage required');const bucket=explicit?opts['ssh-s3-bucket']:opts[b+'-bucket'],region=explicit?opts['ssh-s3-region']:b==='r2'?'auto':opts[b+'-region'];const endpoint=explicit?opts['ssh-s3-endpoint']:b==='r2'?opts['r2-endpoint']:b==='oci'?`https://${opts['oci-namespace']}.compat.objectstorage.${region}.oraclecloud.com`:undefined;demand(typeof bucket==='string'&&bucket.trim()&&typeof region==='string'&&region.trim(),'invalid SSH storage');if(endpoint!==undefined){demand(typeof endpoint==='string'&&/^https:\/\/[^\s\\/?#@]+\/?$/.exec(endpoint)?.[0]===endpoint,'invalid SSH endpoint');const url=new URL(endpoint);demand(url.protocol==='https:'&&!!url.hostname&&!url.username&&!url.password&&!url.search&&!url.hash&&(url.pathname===''||url.pathname==='/'),'invalid SSH endpoint');}return {bucket,region,endpoint,credential_prefix:explicit?'SSH_S3':b==='s3'?null:b.toUpperCase()};}
function merge(target:Map,source:Map){for(const [k,v] of Object.entries(source)){if(!Object.hasOwn(target,k))target[k]=structuredClone(v);else if(object(target[k])&&object(v))merge(target[k],v);else demand(JSON.stringify(target[k])===JSON.stringify(v),'conflicting template '+k);}}
export function node_plan(opts:Map,request:Map){
 demand(object(opts)&&object(request),'invalid node request');demand(!['ssh-key-path','ssh-private-key-path','ssh-public-key-path'].some(k=>Object.hasOwn(opts,k)),'external SSH keys are outside the single-node contract');demand(!Object.hasOwn(opts,'compute-require-existing-state')||typeof opts['compute-require-existing-state']==='boolean','invalid existing-state requirement');demand(!JSON.stringify([opts,request]).includes('${')&&!JSON.stringify([opts,request]).includes('%{')&&!JSON.stringify([opts,request]).includes('\\u0000'),'Terraform expression in caller input');demand(Object.keys(request).every(k=>['node_id','state_filename','workdir','security','network'].includes(k)),'unsupported node field');const layout=node_layout(opts,request),local=opts['provider-backend']==='local';demand(!local||!['ssh-s3-bucket','ssh-s3-region','ssh-s3-endpoint'].some(k=>Object.hasOwn(opts,k)),'local SSH keys belong to local state');const s=local?null:storage(opts),provider=opts['provider-compute'];demand(![(registry.compute as Map)[provider]?.['ssh-setting'],...Object.keys((registry.compute as Map)[provider]?.['ssh-aliases']??{}),provider+'-ssh-private-key'].some(k=>k&&Object.hasOwn(opts,k)),'external SSH keys are outside the single-node contract');demand(!Object.hasOwn(opts,'compute-role-settings'),'topology settings are outside the single-node contract');const recipe=(recipes as Map)[provider];demand(recipe,'unsupported provider');const scoped=opts.profile+'-'+request.node_id;demand(safe(scoped),'combined identity too long');
 const scopedOpts={...opts,profile:scoped},placeholder='ssh-ed25519 COLORS_COMPUTE_REMOTE_KEY';const base={node_id:request.node_id,name:scoped,key:{mode:'managed',public_key:placeholder},network:structuredClone(request.network??{mode:recipe.network_mode}),security:structuredClone(request.security)};
 const sharedDocs=provider_request(scopedOpts,'shared',base).documents,substitutions:Map={[placeholder]:'${tls_private_key.machine.public_key_openssh}'};let ordinal=0;
 function sentinels(v:any):any{if(typeof v==='string'&&v.includes('${')){const token='colors-compute-reference-'+ordinal++;substitutions[token]=v;return token;}if(Array.isArray(v))return v.map(sentinels);if(object(v))return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,sentinels(x)]));return v;}
 const shared:Map={};for(const doc of Object.values(sharedDocs) as Map[])for(const [k,out] of Object.entries(doc.output??{}) as [string,Map][])shared[k]=sentinels(out.value);
 const nodeDocs=provider_request(scopedOpts,'node',base,shared).documents,document:Map={};for(const doc of Object.values(sharedDocs) as Map[]){const value=structuredClone(doc);delete value.output;merge(document,value);}for(const doc of Object.values(nodeDocs) as Map[])merge(document,doc);
 function replace(v:any):any{if(typeof v==='string')return Object.hasOwn(substitutions,v)?substitutions[v]:v;if(Array.isArray(v))return v.map(replace);if(object(v))return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,replace(x)]));return v;}
 const combined=replace(document);combined.terraform??={};combined.terraform.required_providers??={};combined.terraform.required_providers.tls={source:'hashicorp/tls',version:'4.1.0'};if(!local)combined.terraform.required_providers.aws??={source:'hashicorp/aws',version:'6.31.0'};
 if(s){const keys:Map={alias:'keys',region:s.region,access_key:'${var.keys_access_key}',secret_key:'${var.keys_secret_key}'};if(s.endpoint)Object.assign(keys,{endpoints:{s3:s.endpoint},s3_use_path_style:opts['provider-backend']==='r2'&&!Object.hasOwn(opts,'ssh-s3-bucket')?false:true,skip_credentials_validation:true,skip_metadata_api_check:true,skip_region_validation:true,skip_requesting_account_id:true});combined.provider??={};combined.provider.aws=combined.provider.aws?[combined.provider.aws,keys]:[keys];combined.variable={keys_access_key:{type:'string',sensitive:true,default:null},keys_secret_key:{type:'string',sensitive:true,default:null}};}
 for(const [type,rs] of Object.entries(combined.resource??{}) as [string,Map][])for(const name of Object.keys(rs)){const r=combined.resource[type][name];r.depends_on=[...new Set([...(r.depends_on??[]),...(local?['tls_private_key.machine']:['aws_s3_object.ssh_private','aws_s3_object.ssh_public'])])];}
 combined.resource??={};combined.resource.tls_private_key={machine:{algorithm:'ED25519'}};combined.output.compute_identity={value:{profile:opts.profile,node_id:request.node_id,state_filename:request.state_filename,provider}};combined.output.ssh_public_key_fingerprint={value:'${tls_private_key.machine.public_key_fingerprint_sha256}'};
 if(local){combined.output.ssh_private_key={value:'${tls_private_key.machine.private_key_openssh}',sensitive:true};combined.output.ssh_public_key={value:'${tls_private_key.machine.public_key_openssh}'};}else if(s){const resource=(key:string,content:string)=>({provider:'aws.keys',bucket:s.bucket,key,content,force_destroy:false,...(!s.endpoint?{server_side_encryption:'AES256'}:{})});combined.resource.aws_s3_object={ssh_private:resource(layout.key_objects.private,'${tls_private_key.machine.private_key_openssh}'),ssh_public:resource(layout.key_objects.public,'${tls_private_key.machine.public_key_openssh}')};}

 const backend=opts['provider-backend']==='local'?{terraform:{backend:{local:{path:join(layout.directory,request.state_filename)}}}}:backend_plan(opts,layout.state_key).config;return {status:'planned',...layout,documents:{'compute.tf.json':combined,'backend.tf.json':backend}};
}
export function build_node(opts:Map,request:Map){const plan=node_plan(opts,request);directory(plan.directory);const existing=join(plan.directory,'compute.tf.json');if(existsSync(existing)){const previous=JSON.parse(privateRead(existing));demand(previous.output?.compute_identity?.value?.provider===opts['provider-compute'],'existing unit provider cannot change');}const backend=join(plan.directory,'backend.tf.json');if(existsSync(backend))demand(JSON.stringify(JSON.parse(privateRead(backend)))===JSON.stringify(plan.documents['backend.tf.json']),'existing unit backend cannot change');for(const [name,doc] of Object.entries(plan.documents))privateWrite(join(plan.directory,name),JSON.stringify(doc,null,2)+'\n');return {...plan,status:'built'};}
function runtimeEnv(opts:Map,source:Env){const env:Record<string,string>={};for(const [k,v] of Object.entries(source))if(v!==undefined&&!/^(TF_|TOFU_|COLORS_PAR_)/.test(k))env[k]=v;for(const [secret,name] of Object.entries((registry.compute as Map)[opts['provider-compute']]['tofu-env']) as [string,string][]){const value=source['COLORS_PAR_'+secret.toUpperCase().replaceAll('-','_')];demand(value&&value.trim(),'missing compute credential');env[name]=value;}Object.assign(env,{TF_IN_AUTOMATION:'1',TF_INPUT:'0',TF_WORKSPACE:'default'});const s=opts['provider-backend']==='local'?null:storage(opts);if(s?.credential_prefix&&(s.credential_prefix!=='SSH_S3'||source.COLORS_PAR_SSH_S3_ACCESS_KEY_ID||source.COLORS_PAR_SSH_S3_SECRET_ACCESS_KEY))for(const [suffix,key] of [['ACCESS_KEY_ID','keys_access_key'],['SECRET_ACCESS_KEY','keys_secret_key']]){const value=source['COLORS_PAR_'+s.credential_prefix+'_'+suffix];demand(value&&value.trim(),'missing SSH storage credential');env['TF_VAR_'+key]=value;}return env;}
function planAllowed(raw:string,operation:string){const p=JSON.parse(raw);demand(object(p)&&object(p.planned_values)&&typeof p.format_version==='string','invalid plan');const permitted=operation==='delete'?['no-op','read','delete']:['no-op','read','create','update'];demand(Array.isArray(p.resource_changes??[]),'invalid plan');for(const r of p.resource_changes??[])demand(Array.isArray(r.change?.actions)&&r.change.actions.length===1&&permitted.includes(r.change.actions[0]),'replacement refused');}
async function restoreKeys(opts:Map,request:Map,source:Env,runner:BackendRunner,env:Record<string,string>,fingerprint:string,stateOutputs?:Map){
 const layout=node_layout(opts,request),s=opts['provider-backend']==='local'?null:storage(opts),remoteEnv={...env};for(const k of Object.keys(remoteEnv))if(k.startsWith('TF_'))delete remoteEnv[k];if(s?.credential_prefix&&(s.credential_prefix!=='SSH_S3'||source.COLORS_PAR_SSH_S3_ACCESS_KEY_ID||source.COLORS_PAR_SSH_S3_SECRET_ACCESS_KEY)){for(const k of Object.keys(remoteEnv))if(k.startsWith('AWS_')&&k!=='AWS_CA_BUNDLE')delete remoteEnv[k];remoteEnv.AWS_ACCESS_KEY_ID=source['COLORS_PAR_'+s.credential_prefix+'_ACCESS_KEY_ID']!;remoteEnv.AWS_SECRET_ACCESS_KEY=source['COLORS_PAR_'+s.credential_prefix+'_SECRET_ACCESS_KEY']!;}Object.assign(remoteEnv,{AWS_PAGER:'',AWS_CLI_AUTO_PROMPT:'off'});
 const privatePath=join(layout.directory,'ssh-key'),publicPath=privatePath+'.pub',suffix='.'+randomUUID()+'.download',privateTemp=privatePath+suffix,publicTemp=publicPath+suffix;
 try{if(!s){demand(typeof stateOutputs?.ssh_private_key?.value==='string'&&stateOutputs.ssh_private_key.sensitive===true&&typeof stateOutputs?.ssh_public_key?.value==='string','local state keypair missing');privateWrite(privateTemp,stateOutputs.ssh_private_key.value);privateWrite(publicTemp,stateOutputs.ssh_public_key.value);}else for(const [key,file] of [[layout.key_objects.private,privateTemp],[layout.key_objects.public,publicTemp]]){privateWrite(file,'');const r=await runner(['aws','s3api','get-object','--bucket',s.bucket,'--key',key,'--region',s.region,...(s.endpoint?['--endpoint-url',s.endpoint]:[]),file],{cwd:layout.directory,env:remoteEnv,timeoutMs:120000});demand(r.exit===0,'remote key retrieval failed');chmodSync(file,0o600);}const result=await runner(['ssh-keygen','-y','-f',privateTemp],{cwd:layout.directory,env:remoteEnv,timeoutMs:120000}),publicKey=privateRead(publicTemp).trim().split(/\s+/).slice(0,2).join(' ');demand(result.exit===0&&publicKey.startsWith('ssh-ed25519 ')&&result.out.trim().split(/\s+/).slice(0,2).join(' ')===publicKey,'remote key mismatch');const check=await runner(['ssh-keygen','-lf',publicTemp,'-E','sha256'],{cwd:layout.directory,env:remoteEnv,timeoutMs:120000});demand(check.exit===0&&check.out.trim().split(/\s+/)[1]===fingerprint,'remote SSH fingerprint mismatch');renameSync(privateTemp,privatePath);renameSync(publicTemp,publicPath);return privatePath;}catch(error){rmSync(privatePath,{force:true});rmSync(publicPath,{force:true});throw error;}finally{rmSync(privateTemp,{force:true});rmSync(publicTemp,{force:true});}
}
function normalized(params:Map,environment:Env){
 demand(object(params),'invalid compute outputs');const allowed=new Set<string>(['ssh_identity_file']);for(const [stage,documents] of Object.entries((templates as Map)[params.provider]??{}) as [string,Map][])if(stage.startsWith('node'))for(const document of Object.values(documents) as Map[])for(const key of Object.keys(document.output?.params?.value??{}))allowed.add(key);
 demand(Object.keys(params).every(k=>allowed.has(k)),'unexpected compute output');const result=structuredClone(params);for(const k of ['provider','name','ip','user','sudoer'])demand(typeof result[k]==='string'&&result[k].trim(),'incomplete compute outputs');const text=JSON.stringify(result);demand(!text.includes('-----BEGIN ')&&!['"private_key"','"private_key_openssh"','"secret_key"','"access_key"'].some(marker=>text.toLowerCase().includes(marker)),'secret compute output');for(const [k,v] of Object.entries(environment))if(v&&(k.startsWith('COLORS_PAR_')||/SECRET|TOKEN|PASSWORD|ACCESS_KEY|API_KEY/.test(k)))demand(!text.includes(v),'credential compute output');return result;
}
async function statePresence(opts:Map,request:Map,source:Env,runner:BackendRunner,env:Record<string,string>){
 const layout=node_layout(opts,request),b=opts['provider-backend'];
 if(b==='local'){const path=join(layout.directory,request.state_filename);if(!existsSync(path))return false;demand(lstatSync(path).isFile()&&!lstatSync(path).isSymbolicLink(),'unsafe local state');readFileSync(path);return true;}
 const remoteEnv={...env};for(const k of Object.keys(remoteEnv))if(k.startsWith('TF_'))delete remoteEnv[k];
 if(['r2','oci'].includes(b)){for(const k of Object.keys(remoteEnv))if(k.startsWith('AWS_')&&k!=='AWS_CA_BUNDLE')delete remoteEnv[k];remoteEnv.AWS_ACCESS_KEY_ID=source['COLORS_PAR_'+b.toUpperCase()+'_ACCESS_KEY_ID']!;remoteEnv.AWS_SECRET_ACCESS_KEY=source['COLORS_PAR_'+b.toUpperCase()+'_SECRET_ACCESS_KEY']!;}
 const path=join(layout.directory,'.state-probe-'+randomUUID());
 try{privateWrite(path,'');if(b==='gcs'){const r=await runner(['gcloud','storage','cp','gs://'+opts['gcs-bucket']+'/'+layout.state_key+'/default.tfstate',path],{cwd:layout.directory,env:remoteEnv,timeoutMs:120000});if(r.exit===0)return true;demand(/No URLs matched/.test(r.err),'state unreadable');const bucket=await runner(['gcloud','storage','buckets','describe','gs://'+opts['gcs-bucket'],'--format=json'],{cwd:layout.directory,env:remoteEnv,timeoutMs:120000});demand(bucket.exit===0&&JSON.parse(bucket.out).name===opts['gcs-bucket'],'state bucket unreadable');return false;}
 const config=backend_plan(opts,layout.state_key).config.terraform.backend.s3;
 const r=await runner(['aws','s3api','get-object','--bucket',config.bucket,'--key',layout.state_key,'--region',config.region,...(config.endpoints?.s3?['--endpoint-url',config.endpoints.s3]:[]),path],{cwd:layout.directory,env:remoteEnv,timeoutMs:120000});if(r.exit===0)return true;demand(/^\s*(?:aws: \[ERROR\]: )?An error occurred \(NoSuchKey\) when calling the GetObject operation(?: \(reached max retries: [0-9]+\))?:/.test(r.err),'state unreadable');return false;
 }finally{rmSync(path,{force:true});}
}
async function checkRemoteOwnership(opts:Map,request:Map,source:Env,runner:BackendRunner,env:Record<string,string>,state:Map|undefined){
 const layout=node_layout(opts,request),s=storage(opts),remoteEnv={...env};for(const k of Object.keys(remoteEnv))if(k.startsWith('TF_'))delete remoteEnv[k];if(s.credential_prefix&&(s.credential_prefix!=='SSH_S3'||source.COLORS_PAR_SSH_S3_ACCESS_KEY_ID||source.COLORS_PAR_SSH_S3_SECRET_ACCESS_KEY)){for(const k of Object.keys(remoteEnv))if(k.startsWith('AWS_')&&k!=='AWS_CA_BUNDLE')delete remoteEnv[k];remoteEnv.AWS_ACCESS_KEY_ID=source['COLORS_PAR_'+s.credential_prefix+'_ACCESS_KEY_ID']!;remoteEnv.AWS_SECRET_ACCESS_KEY=source['COLORS_PAR_'+s.credential_prefix+'_SECRET_ACCESS_KEY']!;}
 for(const [name,key] of [['ssh_private',layout.key_objects.private],['ssh_public',layout.key_objects.public]]){
 const owned=state?.resources.some((r:Map)=>r.mode==='managed'&&r.type==='aws_s3_object'&&r.name===name&&r.instances?.some((i:Map)=>i.attributes?.key===key&&i.attributes?.bucket===s.bucket));
 if(owned)continue;
 const path=join(layout.directory,'.key-probe-'+randomUUID());try{privateWrite(path,'');const result=await runner(['aws','s3api','get-object','--bucket',s.bucket,'--key',key,'--region',s.region,...(s.endpoint?['--endpoint-url',s.endpoint]:[]),path],{cwd:layout.directory,env:remoteEnv,timeoutMs:120000});demand(result.exit!==0&&/^\s*(?:aws: \[ERROR\]: )?An error occurred \(NoSuchKey\) when calling the GetObject operation(?: \(reached max retries: [0-9]+\))?:/.test(result.err),'remote key without owned state; explicit recovery required');}finally{rmSync(path,{force:true});}
 }
}
export async function compute_node(opts:Map,request:Map,operation='create',environment:Env=process.env,deps:Map={}){
 let credentialPath:string|undefined;try{
 demand(['build','create','inspect','prepare-access','delete'].includes(operation),'unsupported operation');if(operation==='build')return build_node(opts,request);demand(operation!=='delete'||opts['compute-prevent-destroy']===false,'destruction protected');demand(!Object.hasOwn(opts,'compute-require-existing-state')||typeof opts['compute-require-existing-state']==='boolean','invalid existing-state requirement');
 const plan=build_node(opts,request),env=runtimeEnv(opts,environment),runner:BackendRunner=deps.runner??executeBackendCommand,settings:Map={};for(const [variable,option] of Object.entries(backend_plan(opts,plan.state_key).credential_bindings)){demand(environment[variable]?.trim(),'missing backend credential');settings[option]=environment[variable];}credentialPath=join(plan.directory,'credentials.tfbackend.json');privateWrite(credentialPath,JSON.stringify(settings));
 const execute=async(args:string[],timeoutMs=120000)=>{for(const name of ['approved.tfplan','.terraform.lock.hcl',request.state_filename,request.state_filename+'.backup','.terraform/terraform.tfstate']){const path=join(plan.directory,name);try{const st=lstatSync(path);demand(st.isFile()&&!st.isSymbolicLink()&&st.nlink===1,'unsafe OpenTofu file');}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}}const data=join(plan.directory,'.terraform');try{const st=lstatSync(data);demand(st.isDirectory()&&!st.isSymbolicLink(),'unsafe OpenTofu directory');}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}const r=await runner(['tofu',...args],{cwd:plan.directory,env,timeoutMs});for(const file of readdirSync(plan.directory)){const path=join(plan.directory,file);if(lstatSync(path).isFile()&&!lstatSync(path).isSymbolicLink())chmodSync(path,0o600);}demand(r.exit===0,'OpenTofu command failed');return r.out;};await execute(['init','-input=false','-no-color','-reconfigure','-backend-config='+credentialPath]);const present=await statePresence(opts,request,environment,runner,env);const before=present?await execute(['state','pull']):'';let current:Map|undefined;
 if(before.trim()){const raw=JSON.parse(before);if(!(raw.version===4&&raw.serial===0&&raw.lineage===''&&Array.isArray(raw.resources)&&raw.resources.length===0&&object(raw.outputs)&&Object.keys(raw.outputs).length===0))current=parseStateEnvelope(before).document;}
 demand(!current||current.resources.length>0||Object.keys(current.outputs).length===0,'empty resource state has leftover outputs');if(operation==='inspect'&&present&&current&&current.resources.length===0&&Object.keys(current.outputs).length===0)return {status:'destroyed',directory:plan.directory};const populated=current&&current.resources.length>0;const identity={profile:opts.profile,node_id:request.node_id,state_filename:request.state_filename,provider:opts['provider-compute']};if(populated){demand(Object.entries(identity).every(([k,v])=>current!.outputs.compute_identity?.value?.[k]===v),'state identity mismatch; explicit recovery required');}if(operation==='create'&&opts['provider-backend']==='local'&&!present){for(const name of ['ssh-key','ssh-key.pub']){try{lstatSync(join(plan.directory,name));throw Error('local keys without state require recovery');}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}}}if(operation==='create'&&opts['provider-backend']!=='local'){await checkRemoteOwnership(opts,request,environment,runner,env,current);}demand(!populated||current!.outputs.params?.value?.provider===opts['provider-compute'],'state provider mismatch');demand(operation!=='create'||opts['compute-require-existing-state']!==true||populated,'required state absent');
 if(operation==='inspect'||operation==='prepare-access'){demand(populated,'state absent');const params=normalized(current!.outputs.params.value,environment);if(operation==='prepare-access')params.ssh_identity_file=await restoreKeys(opts,request,environment,runner,env,current!.outputs.ssh_public_key_fingerprint?.value,current!.outputs);return {status:'ready',directory:plan.directory,params};}
 if(operation==='delete'&&!populated){demand(present&&current&&Object.keys(current.outputs).length===0,'absent state requires explicit recovery');rmSync(join(plan.directory,'ssh-key'),{force:true});rmSync(join(plan.directory,'ssh-key.pub'),{force:true});return {status:'destroyed',directory:plan.directory};}
 const planPath=join(plan.directory,'approved.tfplan');await execute(['plan','-input=false','-no-color','-out='+planPath,...(operation==='delete'?['-destroy']:[])],1800000);planAllowed(await execute(['show','-json',planPath]),operation);await execute(['apply','-input=false','-no-color',planPath],1800000);const after=await execute(['state','pull']),final=parseStateEnvelope(after);
 if(operation==='delete'){demand(final.document.resources.length===0,'destruction incomplete');rmSync(join(plan.directory,'ssh-key'),{force:true});rmSync(join(plan.directory,'ssh-key.pub'),{force:true});return {status:'destroyed',directory:plan.directory};}
 demand(final.params.provider===opts['provider-compute']&&final.params.node_id===request.node_id&&Object.entries(identity).every(([k,v])=>final.document.outputs.compute_identity?.value?.[k]===v),'invalid compute outputs');const outputs=opts['provider-backend']==='local'?{params:final.params}:stateOutputs(after);const secrets=Object.entries(environment).filter(([k,v])=>v&&(/SECRET|TOKEN|PASSWORD|ACCESS_KEY|API_KEY/.test(k))).map(([,v])=>v!);demand(!secrets.some(v=>JSON.stringify(outputs).includes(v)),'credential in compute output');const key=await restoreKeys(opts,request,environment,runner,env,final.document.outputs.ssh_public_key_fingerprint?.value,final.document.outputs);return {status:'ready',directory:plan.directory,params:{...normalized(final.params,environment),ssh_identity_file:key}};
 }catch(error){if(error instanceof Error&&error.name==='AbortError')throw error;return {status:'error'};}finally{if(credentialPath)rmSync(credentialPath,{force:true});}
}
