import {test,expect} from 'bun:test';import cases from '../../test/fixtures/managed-journal.json';import {managedCoordination,managedDocumentValid} from '../src/managed-journal.ts';
for(const c of cases as any[])test(c.name,()=>{const args=structuredClone(c.args),before=structuredClone(args);if(c.error)expect(()=>managedCoordination(args[0],args[1],args[2])).toThrow(c.error);else{const result=managedCoordination(args[0],args[1],args[2]);expect(result).toEqual(c.expected);expect(managedDocumentValid(result.document)).toBe(true);expect(result.document).not.toHaveProperty('nodes');expect(result.document).not.toHaveProperty('key');}expect(args).toEqual(before);});
import {Coordinator} from '../src/coordinator.ts';
import {documentValid} from '../src/coordination.ts';
test('managed production coordinator serializes real CAS and refuses VM replacement',async()=>{
 const opts={profile:'managed-demo','provider-compute':'vultr','provider-backend':'s3','s3-bucket':'states','s3-region':'us-east-1'};let observed:any={status:'absent'},serial=0;const writes:any[]=[];
 const read=async()=>structuredClone(observed),write=async(intent:any)=>{if(intent.condition.if_none_match==='*'?observed.status!=='absent':intent.condition.if_match!==observed.etag)return {status:'conflict'};expect(documentValid(intent.document)).toBe(true);writes.push(structuredClone(intent));observed={status:'present',etag:`e-${writes.length}`,document:structuredClone(intent.document)};return {status:'written',etag:observed.etag};};
 const owner=new Coordinator(opts,{read,write,eventPrefix:'managed/',idFactory:()=>`m-${++serial}`});await owner.acquire();const attempt=await owner.sharedStart();await expect(owner.release()).rejects.toThrow();await owner.sharedComplete(attempt);await owner.release();expect(observed.document.shared.phase).toBe('ready');expect(observed.document.lock.state).toBe('idle');
 const vm=new Coordinator(opts,{read,write,eventPrefix:'lifecycle/',idFactory:()=>`vm-${++serial}`});await expect(vm.acquire()).rejects.toThrow();expect(observed.document.schema_version).toBe(3);
 const destroy=new Coordinator(opts,{read,write,eventPrefix:'managed/',idFactory:()=>`d-${++serial}`});await destroy.acquire();await destroy.sharedComplete(await destroy.sharedDestroy());await destroy.release();expect(observed.document.status).toBe('retired');expect(observed.document).not.toHaveProperty('nodes');
});
