import {test,expect} from 'bun:test';import {mkdtempSync,rmSync,readFileSync,statSync,symlinkSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {managed_kubernetes,plan_managed_kubernetes,managed_errors,managed_version_preflight,read_managed_kubernetes} from '../src/managed.ts';import {AccessDecoder} from '../src/managed-access.ts';import {Coordinator} from '../src/coordinator.ts';
const opts=(workdir:string)=>({workdir,profile:'demo','provider-compute':'vultr','provider-backend':'s3','s3-bucket':'states','s3-region':'us-east-1','vultr-region':'ewr','vultr-vke-version':'v1.35.2+1','vultr-node-plan':'vc2-2c-4gb','vultr-node-count':2,'compute-prevent-destroy':false});
const params={provider:'vultr',kind:'managed-kubernetes',name:'demo',cluster_id:'cluster-123',endpoint:'https://cluster.example'};
function state(config:any={apiVersion:'v1',kind:'Config',clusters:[{name:'cluster',cluster:{server:params.endpoint}}],users:[{name:'user',user:{token:'cluster-token'}}],contexts:[{name:'active',context:{cluster:'cluster',user:'user'}}],'current-context':'active'}){return JSON.stringify({version:4,serial:1,lineage:'owned',resources:[{}],outputs:{params:{value:params},kubeconfig_b64:{value:Buffer.from(JSON.stringify(config)).toString('base64'),sensitive:true}}});}
test('managed plans own only cluster resources and reject malformed capabilities',()=>{const plan=plan_managed_kubernetes(opts('/tmp'));expect(plan.status).toBe('planned');expect(Object.keys(plan.documents['managed-kubernetes.tf.json'].resource)).toEqual(['vultr_kubernetes']);expect(JSON.stringify(plan)).not.toContain('ssh');for(const delta of [{'vultr-node-count':true},{'vultr-node-count':1.5},{'vultr-vke-version':'${file("secret")}'},{'provider-compute':'aws'},{'compute-prevent-destroy':null}])expect(managed_errors({...opts('/tmp'),...delta}).length).toBeGreaterThan(0);});
test('managed access keeps only public outputs and atomically writes private validated kubeconfig',()=>{const dir=mkdtempSync(join(tmpdir(),'managed-test-'));try{const decoder=new AccessDecoder(opts(dir),{});expect(decoder.decode(state())).toEqual({params});const path=decoder.write();expect(statSync(path).mode&0o777).toBe(0o600);expect(readFileSync(path,'utf8')).toContain('cluster-token');expect(()=>decoder.write()).toThrow();for(const config of [{apiVersion:'v1',kind:'Config',clusters:[{cluster:{server:'http://evil'}}]}, {apiVersion:'v1',kind:'Config',clusters:[{cluster:{server:params.endpoint}}],users:[{user:{exec:{command:'evil'}}}]}])expect(()=>new AccessDecoder(opts(dir),{}).decode(state(config))).toThrow();const other=join(dir,'other');symlinkSync(path,other);expect(statSync(path).mode&0o777).toBe(0o600);}finally{rmSync(dir,{recursive:true,force:true});}});
test('managed access rejects bound credential even inside otherwise valid kubeconfig',()=>{expect(()=>new AccessDecoder(opts('/tmp'),{COLORS_PAR_VULTR_API_KEY:'cluster-token'}).decode(state())).toThrow();});
test('managed native coordinator lease guards create, read, destroy, and schema ownership',async()=>{const dir=mkdtempSync(join(tmpdir(),'managed-runtime-'));let observed:any={status:'absent'},ids=0,present=false;const calls:string[]=[];const read=async()=>structuredClone(observed),write=async(intent:any)=>{if(intent.condition.if_none_match==='*'?observed.status!=='absent':intent.condition.if_match!==observed.etag)return {status:'conflict'};observed={status:'present',etag:`e-${++ids}`,document:structuredClone(intent.document)};return {status:'written',etag:observed.etag};};const dependencies:any={coordinator:(o:any)=>new Coordinator(o,{eventPrefix:'managed/',read,write,idFactory:()=>`id-${++ids}`}),journal_get:read,state_presence:async()=>({status:present?'present':'absent'}),version_preflight:async()=>{calls.push('preflight');return true;},read_managed_state:async()=>{expect(observed.document.lock.state).toBe('held');return {status:'present',params};},converge_state:async(_o:any,_k:any,_d:any,operation:string,_p:any,_e:any,_r:any,_s:any,decoder:Function)=>{expect(observed.document.shared.phase).toBe('running');calls.push(operation);if(operation==='delete'){present=false;return {status:'destroyed'};}present=true;decoder(state());return {status:'ready',params};}};try{const o=opts(dir),env={COLORS_PAR_VULTR_API_KEY:'bound-secret'};expect((await managed_kubernetes(o,{},env,dependencies)).status).toBe('ready');expect(observed.document.lock.state).toBe('idle');expect(calls).toEqual(['preflight','create']);expect((await read_managed_kubernetes(o,{},env,dependencies)).status).toBe('present');expect((await managed_kubernetes({...o,'red/event':'delete'}, {},env,dependencies)).status).toBe('destroyed');expect(observed.document.status).toBe('retired');expect(observed.document).not.toHaveProperty('key');}finally{rmSync(dir,{recursive:true,force:true});}});
test('managed version discovery uses header credential and exact bounded response',async()=>{const o=opts('/tmp'),env={COLORS_PAR_VULTR_API_KEY:'secret'};expect(await managed_version_preflight(o,env,async(url,headers)=>{expect(url).not.toContain('secret');expect(headers.Authorization).toBe('Bearer secret');return Buffer.from(JSON.stringify({versions:['v1.35.2+1']}));})).toBe(true);expect(await managed_version_preflight(o,env,async()=>Buffer.from('{"versions":[]}'))).toBe(false);});

test('managed kubeconfig binds the active context and refuses transport overrides',()=> {
 const config:any={apiVersion:'v1',kind:'Config',clusters:[{name:'cluster',cluster:{server:params.endpoint}}],users:[{name:'user',user:{token:'cluster-token'}}],contexts:[{name:'active',context:{cluster:'cluster',user:'user'}}],'current-context':'active'};
 for(const mutate of [(c:any)=>delete c.contexts,(c:any)=>c['current-context']='wrong',(c:any)=>c.contexts[0].context.user='other',(c:any)=>c.users[0].user={},(c:any)=>c.clusters[0].cluster['proxy-url']='http://localhost:1234',(c:any)=>c.clusters[0].cluster['tls-server-name']='other.example']) {
  const changed=structuredClone(config);mutate(changed);expect(()=>new AccessDecoder(opts('/tmp'),{}).decode(state(changed))).toThrow();
 }
});
