import {expect,test} from 'bun:test';
import {mkdtempSync,realpathSync,rmSync,existsSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import fixtures from '../../test/fixtures/provider-requests.json';
import identity from '../../test/fixtures/public-ssh.json';
import {node_plan,build_node,compute_node,registration_plan,compute_registration} from '../src/node.ts';
const registrations:Record<string,string>={aws:'aws_key_pair',digitalocean:'digitalocean_ssh_key',hcloud:'hcloud_ssh_key',vultr:'vultr_ssh_key'};
const root=()=>realpathSync(mkdtempSync(join(tmpdir(),'compute-node-')));
function sample(workdir:string,provider='digitalocean') {const f=(fixtures as any[]).find(f=>f.args[0]['provider-compute']===provider&&f.args[1]==='shared');return {opts:{...f.args[0],'provider-backend':'local'},request:{workdir,node_id:'app-0',state_filename:'app-0.tfstate',security:f.args[2].security,network:f.args[2].network,ssh_resource:identity,...(registrations[provider]?{ssh_registration:{status:'ready',reference:'registration/fixture',id:'12345',provider,ssh_resource_reference:identity.reference,fingerprint:identity.fingerprint}}:{})}};}
test('all provider/backend plans consume public identities without key ownership',()=>{for(const provider of ['aws','azure','digitalocean','google','hcloud','oci','vultr','yandex'])for(const backend of ['local','r2']){const {opts,request}=sample('/work',provider);const plan=node_plan({...opts,'provider-backend':backend,'r2-bucket':'state','r2-endpoint':'https://example.r2.cloudflarestorage.com','s3-prefix':'infra'},request),d=plan.documents['compute.tf.json'];expect(plan.key_objects).toEqual({});expect(plan.state_key).toBe('infra/'+opts.profile+'/app-0.tfstate');expect(d.output.compute_identity.value.ssh_resource_reference).toBe(identity.reference);for(const token of ['tls_private_key','aws_s3_object','private_key','keys_access_key','sentinel','COLORS_COMPUTE_REMOTE_KEY'])expect(JSON.stringify(d)).not.toContain(token);for(const kind of Object.values(registrations))expect(d.resource[kind]).toBeUndefined();}});
test('registration owns only public provider object',()=>{for(const provider of Object.keys(registrations)){const {opts}=sample('/work',provider),plan=registration_plan(opts,{name:'access',workdir:'/work',state_filename:'registration.tfstate',ssh_resource:identity}),d=plan.documents['compute.tf.json'];expect(Object.keys(d.resource)).toEqual([registrations[provider]]);expect(d.output.compute_identity.value.kind).toBe('ssh-registration');expect(JSON.stringify(d)).toContain(identity.public_key);expect(JSON.stringify(d)).not.toContain('private_key');expect(d.data).toBeUndefined();}});
test('public identity and registration binding are validated',()=>{const {opts,request}=sample('/work');for(const change of [{ssh_resource:{}},{ssh_resource:{...identity,fingerprint:'SHA256:wrong'}},{ssh_registration:{...request.ssh_registration,ssh_resource_reference:'different'}},{node_id:'../escape'},{workdir:'relative'},{state_filename:'../state.tfstate'}])expect(()=>node_plan(opts,{...request,...change})).toThrow();});
function harness(dir:string){const {opts,request}=sample(dir),plan=node_plan(opts,request);let actions=['create'],current:any;const calls:string[][]=[];const state=()=>({version:4,serial:1,lineage:'fixture',resources:[{type:'digitalocean_droplet'}],outputs:{compute_identity:plan.documents['compute.tf.json'].output.compute_identity,params:{value:{provider:'digitalocean',node_id:request.node_id,name:'node',ip:'192.0.2.1',user:'root',sudoer:'root'}}}});const runner=async(args:string[],options:any)=>{calls.push(args);expect(args[0]).toBe('tofu');expect(options.env.COLORS_PAR_SSH_PASSPHRASE).toBeUndefined();expect(options.env.TF_VAR_keys_access_key).toBeUndefined();if(args[1]==='apply'){current=actions[0]==='delete'?{...state(),resources:[],outputs:{}}:state();writeFileSync(join(plan.directory,request.state_filename),JSON.stringify(current));}return {exit:0,out:args[1]==='state'?JSON.stringify(current):args[1]==='show'?JSON.stringify({format_version:'1.2',planned_values:{},resource_changes:[{change:{actions}}]}):'{}',err:''};};return {opts,request,plan,calls,runner,env:{COLORS_PAR_DO_TOKEN:'fixture-secret',COLORS_PAR_SSH_PASSPHRASE:'never-forward'},setActions:(a:string[])=>actions=a};}
test('create inspect delete preserve separate SSH lifetime',async()=>{const dir=root();try{const h=harness(dir),created:any=await compute_node(h.opts,h.request,'create',h.env,{runner:h.runner});expect(created.status).toBe('ready');expect(created.params.ssh_identity_file).toBeUndefined();expect(existsSync(join(h.plan.directory,'ssh-key'))).toBe(false);expect((await compute_node(h.opts,h.request,'inspect',h.env,{runner:h.runner})).status).toBe('ready');h.setActions(['delete']);expect((await compute_node({...h.opts,'compute-prevent-destroy':false},h.request,'delete',h.env,{runner:h.runner})).status).toBe('destroyed');expect(existsSync(join(h.plan.directory,'compute.tf.json'))).toBe(true);}finally{rmSync(dir,{recursive:true,force:true});}});
test('guards reject replacement, missing state and protected deletion',async()=>{for(const mode of ['replace','missing','protected','required']){const dir=root();try{const h=harness(dir);if(mode==='replace')h.setActions(['delete','create']);const opts={...h.opts,...(mode==='missing'?{'compute-prevent-destroy':false}:{}),...(mode==='required'?{'compute-require-existing-state':true}:{})};expect((await compute_node(opts,h.request,['missing','protected'].includes(mode)?'delete':'create',h.env,{runner:h.runner})).status).toBe('error');expect(h.calls.some(c=>c[1]==='apply')).toBe(false);}finally{rmSync(dir,{recursive:true,force:true});}}});
test('backend cannot be rebound and templates persist',()=>{const dir=root();try{const h=harness(dir);build_node(h.opts,h.request);expect(()=>build_node({...h.opts,'provider-backend':'s3','s3-bucket':'other','s3-region':'eu-west-1'},h.request)).toThrow();expect(existsSync(join(h.plan.directory,'compute.tf.json'))).toBe(true);}finally{rmSync(dir,{recursive:true,force:true});}});
test('diagnostics distinguish failed init from uncertain apply',async()=>{for(const command of ['init','apply']){const dir=root();try{const h=harness(dir),result:any=await compute_node(h.opts,h.request,'create',h.env,{runner:async(args:string[],options:any)=>args[1]===command?{exit:126,out:'PRIVATE_STDOUT',err:'No version is set for command tofu\n'}:h.runner(args,options)});expect(result.status).toBe('error');expect(result.error.stage).toBe(command);expect(result.error.infrastructure_changes).toBe(command==='apply'?'possible':'none');expect(JSON.stringify(result)).not.toContain('PRIVATE_STDOUT');}finally{rmSync(dir,{recursive:true,force:true});}}});
test('registration create inspect delete owns no machine or key authority',async()=>{const dir=root();try{const {opts}=sample(dir),request={name:'access',workdir:dir,state_filename:'registration.tfstate',ssh_resource:identity},plan=registration_plan(opts,request);let deleting=false;let state:any={version:4,serial:1,lineage:'registration-test',resources:[{type:'digitalocean_ssh_key'}],outputs:{compute_identity:plan.documents['compute.tf.json'].output.compute_identity,params:{value:{provider:'digitalocean',node_id:'registration-access',id:'12345'}}}};const runner=async(args:string[],options:any)=>{expect(args[0]).toBe('tofu');if(args[1]==='apply'){if(deleting)state={...state,resources:[],outputs:{}};writeFileSync(join(options.cwd,request.state_filename),JSON.stringify(state));}return {exit:0,out:args[1]==='state'?JSON.stringify(state):args[1]==='show'?JSON.stringify({format_version:'1.2',planned_values:{},resource_changes:[{change:{actions:[deleting?'delete':'create']}}]}):'{}',err:''};};const env={COLORS_PAR_DO_TOKEN:'fixture-secret'};const created:any=await compute_registration(opts,request,'create',env,{runner});expect(created.status).toBe('ready');expect(created.id).toBe('12345');expect(created.ssh_resource_reference).toBe(identity.reference);expect((await compute_registration(opts,request,'inspect',env,{runner})).status).toBe('ready');deleting=true;expect((await compute_registration({...opts,'compute-prevent-destroy':false},request,'delete',env,{runner})).status).toBe('destroyed');}finally{rmSync(dir,{recursive:true,force:true});}});
test('uninitialized state never overrides an independent backend presence probe',async()=>{for(const mode of ['absent','present','read-failure','malformed'])for(const operation of ['create','inspect','delete']){const dir=root();try{const h=harness(dir),opts={...h.opts,'provider-backend':'r2','r2-bucket':'fixture','r2-endpoint':'https://fixture.r2.cloudflarestorage.com','compute-prevent-destroy':false};let applied=false;const stub={version:4,terraform_version:'1.11.2',serial:0,lineage:'',outputs:{},resources:[],check_results:null};const calls:string[][]=[];const runner=async(args:string[],options:any)=>{calls.push(args);if(args[0]==='aws')return mode==='absent'?{exit:1,out:'',err:'An error occurred (NoSuchKey) when calling the GetObject operation: missing'}:mode==='read-failure'?{exit:1,out:'',err:'An error occurred (AccessDenied) when calling the GetObject operation: denied'}:{exit:0,out:'{}',err:''};if(args[1]==='state'&&!applied)return {exit:0,out:mode==='malformed'?'{malformed':JSON.stringify(stub),err:''};if(args[1]==='apply')applied=true;return h.runner(args,options);};const result=await compute_node(opts,h.request,operation,{...h.env,COLORS_PAR_R2_ACCESS_KEY_ID:'fixture-access',COLORS_PAR_R2_SECRET_ACCESS_KEY:'fixture-secret'},{runner});expect(result.status).toBe(mode==='absent'&&operation==='create'?'ready':'error');expect(applied).toBe(mode==='absent'&&operation==='create');expect(calls.some(c=>c[0]==='aws')).toBe(true);}finally{rmSync(dir,{recursive:true,force:true});}}});
