import {expect,test} from 'bun:test';
import {mkdtempSync,symlinkSync,linkSync,unlinkSync,realpathSync,rmSync,existsSync,readFileSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import fixtures from '../../test/fixtures/provider-requests.json';
import {node_plan,build_node,compute_node} from '../src/node.ts';
const root=()=>realpathSync(mkdtempSync(join(tmpdir(),'compute-node-')));
function sample(workdir:string,provider='vultr'){
 const f=(fixtures as any[]).find(f=>f.name===provider+'-shared');const opts={...f.args[0],'provider-backend':'s3','s3-bucket':'states','s3-region':'eu-west-1','s3-prefix':'infrastructure'};const request={workdir,node_id:'app-0',state_filename:'app-0.tfstate',security:f.args[2].security,network:f.args[2].network};return {opts,request};
}
test('single node plans join owned infrastructure and remote keys with stable paths',()=>{for(const provider of ['aws','vultr','digitalocean','hcloud','google','azure','oci','yandex']){const f=(fixtures as any[]).find(f=>f.name===provider+'-shared');if(!f)continue;const {opts,request}=sample('/work',provider),p=node_plan(opts,request),d=p.documents['compute.tf.json'];expect(p.directory).toBe('/work/'+opts.profile+'/app-0');expect(p.state_key).toBe('infrastructure/'+opts.profile+'/app-0.tfstate');expect(d.resource.tls_private_key.machine.algorithm).toBe('ED25519');expect(d.resource.aws_s3_object.ssh_private.content).toBe('${tls_private_key.machine.private_key_openssh}');expect(JSON.stringify(d)).not.toContain('colors-compute-reference-');expect(JSON.stringify(d)).not.toContain('COLORS_COMPUTE_REMOTE_KEY');}});
test('build keeps templates and uses distinct profile/node directory',()=>{const dir=root();try{const {opts,request}=sample(dir);const p=build_node(opts,request);expect(existsSync(join(p.directory,'compute.tf.json'))).toBe(true);expect(build_node(opts,request).directory).toBe(p.directory);expect(node_plan(opts,{...request,node_id:'app-1',state_filename:'app-1.tfstate'}).state_key).not.toBe(p.state_key);}finally{rmSync(dir,{recursive:true,force:true});}});
test('runtime reuses SDK cwd/default tofu data and refreshes remote keys',async()=>{const dir=root();try{const {opts,request}=sample(dir);const p=build_node(opts,request);writeFileSync(join(p.directory,'ssh-key'),'STALE');let applied=false;const calls:string[][]=[];const state={version:4,serial:1,lineage:'x',resources:[{type:'vultr_instance'}],outputs:{compute_identity:{value:{profile:opts.profile,node_id:request.node_id,state_filename:request.state_filename,provider:'vultr'}},ssh_public_key_fingerprint:{value:'SHA256:fixture'},params:{value:{provider:'vultr',node_id:request.node_id,name:'demo-app-0',user:'root',sudoer:'root',ip:'192.0.2.1'}}}};const result=await compute_node(opts,request,'create',{COLORS_PAR_VULTR_API_KEY:'fixture-credential-secret',TF_DATA_DIR:'/wrong',TF_CLI_ARGS:'-lock=false'},{runner:async(args:string[],options:any)=>{calls.push(args);expect(options.cwd).toBe(p.directory);expect(options.env.TF_DATA_DIR).toBeUndefined();expect(options.env.TF_CLI_ARGS).toBeUndefined();if(args[0]==='aws'&&(args.at(-1)!.includes('.key-probe-')||args.at(-1)!.includes('.state-probe-')))return {exit:1,out:'',err:'An error occurred (NoSuchKey) when calling the GetObject operation: missing'};if(args[0]==='aws'){writeFileSync(args.at(-1)!,args.includes(p.key_objects.public)?'ssh-ed25519 AAAA':'REMOTE');return {exit:0,out:'{}',err:''};}if(args[0]==='ssh-keygen')return {exit:0,out:args.includes('-lf')?'256 SHA256:fixture fixture (ED25519)':'ssh-ed25519 AAAA',err:''};if(args[1]==='apply')applied=true;return {exit:0,out:args[1]==='state'?(applied?JSON.stringify(state):''):args[1]==='show'?JSON.stringify({format_version:'1.2',planned_values:{},resource_changes:[{change:{actions:['create']}}]}):'',err:''};}});expect(result.status).toBe('ready');expect(readFileSync(join(p.directory,'ssh-key'),'utf8')).toBe('REMOTE');expect(existsSync(join(p.directory,'compute.tf.json'))).toBe(true);expect(existsSync(join(p.directory,'credentials.tfbackend.json'))).toBe(false);}finally{rmSync(dir,{recursive:true,force:true});}});
function harness(workdir:string,settings:any={}){
 const {opts,request}=sample(workdir),plan=node_plan(opts,request);const calls:string[][]=[];let applied=false;
 const identity={profile:opts.profile,node_id:request.node_id,state_filename:request.state_filename,provider:'vultr'};
 const state={version:4,serial:1,lineage:'fixture',resources:[{mode:'managed',type:'vultr_instance',name:'node'},...['private','public'].map(kind=>({mode:'managed',type:'aws_s3_object',name:'ssh_'+kind,instances:[{attributes:{bucket:'states',key:plan.key_objects[kind as 'private'|'public']}}]}))],outputs:{compute_identity:{value:identity},ssh_public_key_fingerprint:{value:'SHA256:node'},params:{value:{provider:settings.provider??'vultr',node_id:request.node_id,name:'demo-app-0',user:'root',sudoer:'root',ip:'192.0.2.1'}}}};
 const runner=async(args:string[],options:any)=>{calls.push(args);const ok=(out='')=>({exit:0,out,err:''});if(args[0]==='aws'){
  if(args.at(-1)!.includes('.state-probe-'))return settings.stateError?{exit:1,out:'',err:'An error occurred (NoSuchBucket) when calling the GetObject operation: missing bucket'}:settings.absent?{exit:1,out:'',err:'An error occurred (NoSuchKey) when calling the GetObject operation: absent'}:ok('{}');
  if(args.at(-1)!.includes('.key-probe-'))return settings.orphan?ok('{}'):{exit:1,out:'',err:'An error occurred (NoSuchKey) when calling the GetObject operation: absent'};
  if(settings.keyError&&args.includes(plan.key_objects.public))return {exit:1,out:'',err:'denied'};writeFileSync(args.at(-1)!,args.includes(plan.key_objects.public)?'ssh-ed25519 AAAA':'REMOTE');return ok('{}');
 }if(args[0]==='ssh-keygen')return ok(args.includes('-lf')?'256 '+(settings.badFingerprint?'SHA256:wrong':'SHA256:node')+' label (ED25519)':'ssh-ed25519 AAAA');
 if(args[1]==='state')return ok(JSON.stringify(applied&&settings.deleting?{...state,resources:[],outputs:{}}:state));
 if(args[1]==='show')return ok(JSON.stringify({format_version:'1.2',planned_values:{},resource_changes:[{change:{actions:settings.actions??[settings.deleting?'delete':'update']}}]}));
 if(args[1]==='apply'){if(settings.cancel)throw new DOMException('cancelled','AbortError');applied=true;}return ok();};
 return {opts,request,plan,calls,runner,env:{COLORS_PAR_VULTR_API_KEY:'fixture-credential-secret'}};
}
test('state read errors, provider mismatch, replacements and orphan keys refuse mutations',async()=>{for(const settings of [{stateError:true},{provider:'aws'},{actions:['delete','create']},{absent:true,orphan:true}]){const dir=root();try{const h=harness(dir,settings);expect((await compute_node(h.opts,h.request,'create',h.env,{runner:h.runner})).status).toBe('error');expect(h.calls.some(c=>c[1]==='apply')).toBe(false);}finally{rmSync(dir,{recursive:true,force:true});}}});
test('failed remote retrieval or fingerprint validation removes stale local access',async()=>{for(const settings of [{keyError:true},{badFingerprint:true}]){const dir=root();try{const h=harness(dir,settings);build_node(h.opts,h.request);writeFileSync(join(h.plan.directory,'ssh-key'),'STALE');writeFileSync(join(h.plan.directory,'ssh-key.pub'),'STALE');expect((await compute_node(h.opts,h.request,'prepare-access',h.env,{runner:h.runner})).status).toBe('error');expect(existsSync(join(h.plan.directory,'ssh-key'))).toBe(false);expect(existsSync(join(h.plan.directory,'ssh-key.pub'))).toBe(false);}finally{rmSync(dir,{recursive:true,force:true});}}});
test('guarded deletion retains templates and removes copies only after confirmed destroy',async()=>{const dir=root();try{const h=harness(dir,{deleting:true});build_node(h.opts,h.request);writeFileSync(join(h.plan.directory,'ssh-key'),'COPY');expect((await compute_node(h.opts,h.request,'delete',h.env,{runner:h.runner})).status).toBe('error');expect(h.calls.length).toBe(0);expect(existsSync(join(h.plan.directory,'ssh-key'))).toBe(true);expect((await compute_node({...h.opts,'compute-prevent-destroy':false},h.request,'delete',h.env,{runner:h.runner})).status).toBe('destroyed');expect(existsSync(join(h.plan.directory,'compute.tf.json'))).toBe(true);expect(existsSync(join(h.plan.directory,'ssh-key'))).toBe(false);}finally{rmSync(dir,{recursive:true,force:true});}});
test('cancellation preserves persistent root and never starts remote key access',async()=>{const dir=root();try{const h=harness(dir,{cancel:true});await expect(compute_node(h.opts,h.request,'create',h.env,{runner:h.runner})).rejects.toThrow('cancelled');expect(existsSync(join(h.plan.directory,'compute.tf.json'))).toBe(true);expect(h.calls.some(c=>c[0]==='ssh-keygen')).toBe(false);}finally{rmSync(dir,{recursive:true,force:true});}});
test('identity/path/injection inputs are refused before writing',()=>{const {opts,request}=sample('/work');for(const change of [{node_id:'../other'},{node_id:'app\n'},{state_filename:'../x.tfstate'},{state_filename:'x.tfstate\n'},{workdir:'/work/../other'},{workdir:'relative'},{roles:{}},{security:{...request.security,egress:'${file("secret")}'}}])expect(()=>node_plan(opts,{...request,...change})).toThrow();});

test('template writes refuse dangling symlinks and hardlinks without modifying outside files',()=>{for(const kind of ['dangling','hardlink']){const dir=root();try{const h=harness(dir);build_node(h.opts,h.request);const template=join(h.plan.directory,'compute.tf.json'),outside=join(dir,'outside');unlinkSync(template);if(kind==='dangling')symlinkSync(outside,template);else{writeFileSync(outside,'outside remains');linkSync(outside,template);}expect(()=>build_node(h.opts,h.request)).toThrow();expect(kind==='dangling'?existsSync(outside):readFileSync(outside,'utf8')).toBe(kind==='dangling'?false:'outside remains');}finally{rmSync(dir,{recursive:true,force:true});}}});
test('delete with absent remote state refuses and retains local key copy',async()=>{const dir=root();try{const h=harness(dir,{absent:true,deleting:true});build_node(h.opts,h.request);writeFileSync(join(h.plan.directory,'ssh-key'),'COPY');expect((await compute_node({...h.opts,'compute-prevent-destroy':false},h.request,'delete',h.env,{runner:h.runner})).status).toBe('error');expect(readFileSync(join(h.plan.directory,'ssh-key'),'utf8')).toBe('COPY');expect(h.calls.some(c=>c[1]==='apply')).toBe(false);}finally{rmSync(dir,{recursive:true,force:true});}});
test('inspection preserves approved provider-specific node fields without key retrieval',async()=>{for(const provider of ['azure','hcloud']){const dir=root();try{const {opts,request}=sample(dir,provider),plan=node_plan(opts,request);const extra=provider==='azure'?{nic_id:'nic',vm_id:'vm',subnet_id:'subnet'}:{server_id:'server',network_attachment_id:'attachment'};const state={version:4,serial:1,lineage:'fixture',resources:[{type:provider+'_resource'}],outputs:{compute_identity:{value:{profile:opts.profile,node_id:request.node_id,state_filename:request.state_filename,provider}},params:{value:{provider,node_id:request.node_id,name:'node',ip:'192.0.2.1',user:'root',sudoer:'root',...extra}}}};const {registry}=await import('../src/index.ts');const env=Object.fromEntries((registry.compute as any)[provider].secrets.map((k:string)=>['COLORS_PAR_'+k.toUpperCase().replaceAll('-','_'),'fixture-credential-'+k]));const calls:string[][]=[];const result=await compute_node(opts,request,'inspect',env,{runner:async(args:string[])=>{calls.push(args);return {exit:0,out:args[1]==='state'?JSON.stringify(state):'{}',err:''};}});expect(result.status).toBe('ready');for(const [k,v] of Object.entries(extra))expect((result as any).params[k]).toBe(v);expect(calls.some(c=>c[0]==='ssh-keygen')).toBe(false);}finally{rmSync(dir,{recursive:true,force:true});}}});
test('remote key provider alias follows backend addressing without replacing compute AWS provider',()=>{const {opts,request}=sample('/work','aws');const cases=[{backend:'r2',settings:{'r2-bucket':'states','r2-endpoint':'https://account.r2.cloudflarestorage.com'},pathStyle:false},{backend:'oci',settings:{'oci-bucket':'states','oci-region':'eu-frankfurt-1','oci-namespace':'tenant'},pathStyle:true},{backend:'gcs',settings:{'gcs-bucket':'states','gcs-region':'eu-west-1','google-project':'project','ssh-s3-bucket':'keys','ssh-s3-region':'eu-west-1','ssh-s3-endpoint':'https://storage.example.com'},pathStyle:true}];for(const c of cases){const plan=node_plan({...opts,'provider-backend':c.backend,...c.settings},request),providers=plan.documents['compute.tf.json'].provider.aws;expect(providers).toHaveLength(2);expect(providers[0].region).toBe(opts['aws-region']);expect(providers[0].alias).toBeUndefined();expect(providers[1].alias).toBe('keys');expect(providers[1].s3_use_path_style).toBe(c.pathStyle);expect(providers[1].access_key).toBe('${var.keys_access_key}');}});
test('S3-compatible key authority cannot be redirected and explicit endpoints are validated',()=>{const {opts,request}=sample('/work');for(const backend of ['s3','r2','oci'])for(const key of ['ssh-s3-bucket','ssh-s3-region','ssh-s3-endpoint'])expect(()=>node_plan({...opts,'provider-backend':backend,[key]:'other'},request)).toThrow();const local={...opts,'provider-backend':'gcs','gcs-bucket':'states','gcs-region':'eu-west-1','google-project':'project','ssh-s3-bucket':'keys','ssh-s3-region':'eu-west-1'};for(const endpoint of ['http://storage.example','https://user:password@storage.example','https://storage.example/path','https://storage.example/a/..','https://storage.example?','https://storage.example#','https://storage.example?token=x','https://storage.example#fragment','https://'])expect(()=>node_plan({...local,'ssh-s3-endpoint':endpoint},request)).toThrow();for(const key of ['ssh-s3-bucket','ssh-s3-region'])for(const value of ['', '   ',null])expect(()=>node_plan({...local,[key]:value},request)).toThrow();expect(node_plan({...local,'ssh-s3-endpoint':'https://storage.example/'},request).status).toBe('planned');});
test('local backend owns TLS keys in local state and needs no object storage',()=>{for(const provider of ['vultr','aws']){const {opts,request}=sample('/work',provider);const p=node_plan({...opts,'provider-backend':'local'},request),d=p.documents['compute.tf.json'];expect(p.key_objects).toEqual({});expect(d.resource.aws_s3_object).toBeUndefined();expect(d.variable).toBeUndefined();expect(d.output.ssh_private_key).toEqual({value:'${tls_private_key.machine.private_key_openssh}',sensitive:true});expect(d.output.ssh_public_key).toEqual({value:'${tls_private_key.machine.public_key_openssh}'});expect(d.provider.aws?.alias).toBeUndefined();expect(Array.isArray(d.provider.aws)).toBe(false);if(provider==='vultr')expect(d.terraform.required_providers.aws).toBeUndefined();for(const key of ['ssh-s3-bucket','ssh-s3-region','ssh-s3-endpoint'])expect(()=>node_plan({...opts,'provider-backend':'local',[key]:'override'},request)).toThrow();}});
test('local access always overwrites copies from authoritative state and never invokes S3',async()=>{const dir=root();try{const input=sample(dir),opts={...input.opts,'provider-backend':'local'},request=input.request,p=build_node(opts,request);const state={version:4,serial:1,lineage:'local',resources:[{type:'vultr_instance'}],outputs:{compute_identity:{value:{profile:opts.profile,node_id:request.node_id,state_filename:request.state_filename,provider:'vultr'}},ssh_private_key:{value:'LOCAL-STATE-PRIVATE',sensitive:true},ssh_public_key:{value:'ssh-ed25519 AAAA',sensitive:true},ssh_public_key_fingerprint:{value:'SHA256:local'},params:{value:{provider:'vultr',node_id:request.node_id,name:'node',ip:'192.0.2.1',user:'root',sudoer:'root'}}}};writeFileSync(join(p.directory,request.state_filename),JSON.stringify(state));writeFileSync(join(p.directory,'ssh-key'),'STALE');const calls:string[][]=[];const result=await compute_node(opts,request,'prepare-access',{COLORS_PAR_VULTR_API_KEY:'fixture-token'},{runner:async(args:string[],options:any)=>{calls.push(args);expect(options.env.TF_VAR_keys_access_key).toBeUndefined();expect(args[0]).not.toBe('aws');return {exit:0,out:args[0]==='ssh-keygen'?(args.includes('-lf')?'256 SHA256:local fixture':'ssh-ed25519 AAAA'):args[1]==='state'?JSON.stringify(state):'{}',err:''};}});expect(result.status).toBe('ready');expect(readFileSync(join(p.directory,'ssh-key'),'utf8')).toBe('LOCAL-STATE-PRIVATE');expect(JSON.stringify(result)).not.toContain('LOCAL-STATE-PRIVATE');expect(calls.some(c=>c[0]==='aws')).toBe(false);}finally{rmSync(dir,{recursive:true,force:true});}});
test('local keys without state refuse create and preserve recovery copies',async()=>{const dir=root();try{const input=sample(dir),opts={...input.opts,'provider-backend':'local'},p=build_node(opts,input.request);writeFileSync(join(p.directory,'ssh-key'),'RECOVERY');const calls:string[][]=[];const result=await compute_node(opts,input.request,'create',{COLORS_PAR_VULTR_API_KEY:'fixture-token'},{runner:async(args:string[])=>{calls.push(args);return {exit:0,out:'{}',err:''};}});expect(result.status).toBe('error');expect(readFileSync(join(p.directory,'ssh-key'),'utf8')).toBe('RECOVERY');expect(calls.some(c=>c[1]==='apply')).toBe(false);}finally{rmSync(dir,{recursive:true,force:true});}});
test('fresh local create and delete keep key lifecycle entirely within local state',async()=>{const dir=root();try{const input=sample(dir),opts={...input.opts,'provider-backend':'local'},request=input.request,p=node_plan(opts,request);const state={version:4,serial:1,lineage:'local',resources:[{type:'vultr_instance'}],outputs:{compute_identity:{value:{profile:opts.profile,node_id:request.node_id,state_filename:request.state_filename,provider:'vultr'}},ssh_private_key:{value:'LOCAL-PRIVATE',sensitive:true},ssh_public_key:{value:'ssh-ed25519 AAAA'},ssh_public_key_fingerprint:{value:'SHA256:local'},params:{value:{provider:'vultr',node_id:request.node_id,name:'node',ip:'192.0.2.1',user:'root',sudoer:'root'}}}};let deleting=false,current:any=state;const env={COLORS_PAR_VULTR_API_KEY:'fixture-token'};const runner=async(args:string[])=>{expect(args[0]).not.toBe('aws');if(args[1]==='apply'){current=deleting?{...state,resources:[],outputs:{}}:state;writeFileSync(join(p.directory,request.state_filename),JSON.stringify(current));}return {exit:0,out:args[0]==='ssh-keygen'?(args.includes('-lf')?'256 SHA256:local fixture':'ssh-ed25519 AAAA'):args[1]==='state'?JSON.stringify(current):args[1]==='show'?JSON.stringify({format_version:'1.2',planned_values:{},resource_changes:[{change:{actions:[deleting?'delete':'create']}}]}):'{}',err:''};};const created=await compute_node(opts,request,'create',env,{runner});expect(created.status).toBe('ready');expect(JSON.stringify(created)).not.toContain('LOCAL-PRIVATE');expect(readFileSync(join(p.directory,'ssh-key'),'utf8')).toBe('LOCAL-PRIVATE');deleting=true;expect((await compute_node({...opts,'compute-prevent-destroy':false},request,'delete',env,{runner})).status).toBe('destroyed');expect(existsSync(join(p.directory,'ssh-key'))).toBe(false);expect(existsSync(join(p.directory,'compute.tf.json'))).toBe(true);}finally{rmSync(dir,{recursive:true,force:true});}});

test('inspect confirms strictly empty state without mutation but access and inconsistent state refuse',async()=>{for(const mode of ['empty','leftover','absent'])for(const operation of ['inspect','prepare-access','create','delete']){if(mode==='empty'&&['create','delete'].includes(operation))continue;const dir=root();try{const h=harness(dir),opts={...h.opts,'compute-prevent-destroy':false};const calls:string[][]=[];const state={version:4,serial:3,lineage:'state',resources:[],outputs:mode==='leftover'?{params:{value:{provider:'vultr'}}}:{}};const result=await compute_node(opts,h.request,operation,h.env,{runner:async(args:string[])=>{calls.push(args);if(args[0]==='aws'&&mode==='absent')return {exit:1,out:'',err:'An error occurred (NoSuchKey) when calling the GetObject operation: absent'};return {exit:0,out:args[1]==='state'?JSON.stringify(state):'{}',err:''};}});expect(result.status).toBe(mode==='empty'&&operation==='inspect'?'destroyed':'error');expect(calls.some(c=>c[1]==='apply'||c[0]==='ssh-keygen')).toBe(false);}finally{rmSync(dir,{recursive:true,force:true});}}});
